/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ActivitiesIndexRouteImport } from './routes/activities.index'
import { Route as ActivitiesSlugRouteImport } from './routes/activities.$slug'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSignupsDotcsvRouteImport } from './routes/admin.signups[.]csv'
import { Route as AdminApiSignupsRouteImport } from './routes/admin.api.signups'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesSlugRoute = ActivitiesSlugRouteImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupsDotcsvRoute = AdminSignupsDotcsvRouteImport.update({
  id: '/admin/signups.csv',
  path: '/admin/signups.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiSignupsRoute = AdminApiSignupsRouteImport.update({
  id: '/admin/api/signups',
  path: '/admin/api/signups',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/signups.csv': typeof AdminSignupsDotcsvRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/api/signups': typeof AdminApiSignupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/signups.csv': typeof AdminSignupsDotcsvRoute
  '/activities': typeof ActivitiesIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/api/signups': typeof AdminApiSignupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/admin/signups.csv': typeof AdminSignupsDotcsvRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/api/signups': typeof AdminApiSignupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/activities/$slug'
    | '/admin/signups.csv'
    | '/activities/'
    | '/admin/'
    | '/admin/api/signups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/activities/$slug'
    | '/admin/signups.csv'
    | '/activities'
    | '/admin'
    | '/admin/api/signups'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/activities/$slug'
    | '/admin/signups.csv'
    | '/activities/'
    | '/admin/'
    | '/admin/api/signups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  ActivitiesSlugRoute: typeof ActivitiesSlugRoute
  AdminSignupsDotcsvRoute: typeof AdminSignupsDotcsvRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApiSignupsRoute: typeof AdminApiSignupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$slug': {
      id: '/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signups.csv': {
      id: '/admin/signups.csv'
      path: '/admin/signups.csv'
      fullPath: '/admin/signups.csv'
      preLoaderRoute: typeof AdminSignupsDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api/signups': {
      id: '/admin/api/signups'
      path: '/admin/api/signups'
      fullPath: '/admin/api/signups'
      preLoaderRoute: typeof AdminApiSignupsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  ActivitiesSlugRoute: ActivitiesSlugRoute,
  AdminSignupsDotcsvRoute: AdminSignupsDotcsvRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminApiSignupsRoute: AdminApiSignupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
